name: taxi_go_user_version
description: "Taxi Go is Flutter App Was Created  By Craft Code Company"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  auto_size_text: null
  cupertino_icons: null
  dropdown_button2: ^2.3.9
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: null
  font_awesome_flutter: ^10.8.0
  google_fonts: null
  intl: any

dev_dependencies:
  flutter_launcher_icons: null
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/taxi_go_icon.jpg"
  remove_alpha: true
  adaptive_icon_background: "#1D1AD8"
  adaptive_icon_foreground: "assets/icons/taxi_go_icon.jpg"
